### PR TITLE
Remove Vital from Alternatives list in an attempt to fix #101

### LINKED ISSUE #101: Conflict of interest?
Raised by @TheKodeToad in the Prism Discord

Technically, Vital makes money (albeit only to devin) from Modrinth ad revenue, so it could come across as a CoI because we are "competing" against Essential (though not actually)

The minimum to address this might be removing the Vital modpack from the /alternatives page, but suggestions are open on how to figure this one out

### PR DESCRIPTION
**Pull request by KTrain5169**
note to self: nuke/remake the PR template

### CODE REVIEW

**Review by blryface — APPROVED** [review]
LGTM although the title could've been worded a lot better. This is why I edited it.

**Comment by KTrain5169** [comment]
fair enough

do we merge or wait for pixel

**Comment by blryface** [comment]
Pretty sure there's a specific reason why you made the Branch Protection Rule need me *and* pixel to approve it

**Comment by KTrain5169** [comment]
It doesn't, I just requested it myself

**Comment by blryface** [comment]
seeing as pixel is probably busy around this time, I think we should just merge it.

**Pull request merged**
