### PR TITLE
Fix GitHub link in index.vue

### LINKED ISSUE #120: GitHub link on main page incorrect
## Describe the bug here

At the bottom of the main page (https://notessential.blurry.gay/) it contains a link to the GitHub, however, the link there is incorrect and has `uesvital` instead of `usevital`.
image
image
This could be used by someone maliciously. 

The affected line is here:
https://github.com/usevital/notessential/blob/788e9f9fd50b938fea0a232bdcb71ba3e2eece6a/pages/index.vue#L35

## Steps to reproduce

Step 1: Go to https://notessential.blurry.gay/
Step 2: Scroll to bottom
Step 3: Click on GitHub link

## Expected result

It links to this repo.

### Additional info

N/A

## Checklist

- [x] I have clearly and, to the best of my ability, accurately stated info about the bug I'm experiencing.
- [x] I have searched for duplicate issues and have not found any.
- [ ] I did not read this section.

### PR DESCRIPTION
**Pull request by Thinkseal**
Site changes:

Fix the GitHub link in index.vue

Resolves #120 

- [X] I have clearly stated why I want this to be changed.
- [X] For major changes, I have clearly stated what they are and why I've done them.
- [X] Any new resources put in are safe and not malicious.
- [X] I have searched for duplicate PRs and have not found any.

### CODE REVIEW

**Review by Nitrrine — APPROVED** [review]
LGTM

**Comment by blryface** [comment]
edit: changed Seal's comment to be better™

**Review by blryface — APPROVED** [review]
uesvital (lgtm)

**Comment by blryface** [comment]
I hate the merge rules and having to make PRs to change literally 2 characters

**Pull request merged**
